export const places = [
    {
        id: 1,
        name: "Cơm Tấm Cô Ba",
        type: "Quán ăn",
        categoryIcon: "restaurant",
        rating: 4.8,
        distance: "500m",
        location: "Làng Đại học, Thủ Đức",
        price: "25.000đ - 45.000đ",
        priceValue: 45000,
        nearUniversities: ["ĐH Quốc gia TP.HCM", "ĐH Bách Khoa"],
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCJeojFugANtwKPL3n-1MhJ4bTM3qFe7gigN_stqpKONZLnxx0RoVgfBg36kfeF9ukIBl_0WQDgfi8JU4sGwpnXl32TZgRfN8phrbgmB5R9fkpusmFIqZYY_MQ5YgdM6FrPJIoDwe_bKsqyWr4WevUD0k1bYUuCYdeO1PvSv3mPVaOH9mpYzqHvzq5DxknKMCneydc-9gaOkvvUrCR4IXUibrBLeOgsUdfrE89ubYO28CKozTXSG52rmeNJEZf_ROvmnOmCsn1zPMq3",
        status: "Đang mở cửa",
        statusColor: "bg-green-500",
        description: "Nhà hàng truyền thống với cơm tấm sườn nướng siêu ngon.",
        phone: "090 123 4567"
    },
    {
        id: 2,
        name: "Uni Coffee & Study",
        type: "Quán ăn",
        categoryIcon: "restaurant",
        rating: 4.5,
        distance: "200m",
        location: "Khu A, KTX ĐHQG",
        price: "15.000đ - 35.000đ",
        priceValue: 35000,
        nearUniversities: ["ĐH Quốc gia TP.HCM", "ĐH Ngoại thương"],
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAo4QDHyv-tzk8tVJSfi5xVeZ8efbgCwxvRVTha8iV5m6qaIIyoAmoJHiPkBEHHg24zshQXs7R0u33WYF7xt-0M3LlCH4898lr_pbisIO7taYROJxAvBB01-L8l5CxmKs9awmzxh52r7BTE_WNG_86929MlZq8hphKebnNiaMyYHKDJtoE4qvpmeBiTQTMDx7X4wTNeMi7-Tt6tY_Nf2tj8atv7wlg1KXG2LobQj98v_ZYeGGmFRm1pGgwNweligVfRvqkJX1KB6e6N",
        status: "Chờ 15 phút",
        statusColor: "bg-slate-500",
        description: "LocalUni là điểm đến lý tưởng dành cho sinh viên và freelancer cần tìm một không gian làm việc tập trung. Quán được trang bị wifi 6 tốc độ cao, hệ thống ổ cắm điện tại mọi bàn.",
        phone: "090 123 4567"
    },
    {
        id: 3,
        name: "Nhà trọ BlueSky",
        type: "Phòng trọ",
        categoryIcon: "bed",
        rating: 4.2,
        distance: "1.2km",
        location: "Đường số 8, Linh Trung",
        price: "2.500.000đ/tháng",
        priceValue: 2500000,
        nearUniversities: ["ĐH Quốc gia TP.HCM", "ĐH Kinh tế Quốc dân", "ĐH Bách Khoa"],
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuABwD3yYhTVvDa3SYp7aAKiTXsP5HsKsAkfRHxh0u6-2S99JQLo0DxTD7ZyOeQYBSqBN6jV5X-1RwoBlC_dxeQaLxiKbMc8wGtm195oDYHUB1GUa3tQBvk3yRpvv6TozmR8rEhtFokjJw8yuaP2xCxYfl0D3v4KFj3h6XJKBGMf9UdxNkRWjSg9ROKVWu0FMAaGUwx9OxPXdPSt_nAUk_bFcy-IPMYDDIYQf6mJBNpZItKgjQsFTv5YzFqWm5pH9z90CgZN6qBOjmOe",
        description: "Nhà trọ BlueSky với đầy đủ tiện nghi, giờ giấc tự do, an ninh đảm bảo.",
        phone: "090 123 4567"
    },
    {
        id: 4,
        name: "Tiệm Photocopy 247",
        type: "Dịch vụ",
        categoryIcon: "home_repair_service",
        rating: 4.9,
        distance: "100m",
        location: "Đối diện cổng ĐH Bách Khoa",
        price: "500đ/trang",
        priceValue: 500,
        nearUniversities: ["ĐH Bách Khoa", "ĐH Ngoại thương"],
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBkQNcyOlct3M6TsTjiMYsg_Z1YU5hEGeISpapJsFdX2BAwqbQVpVbky0_WIzVIFINxJxV9TvY7aBNqCkass2O4vzwZCIrV2ghGtJQGcwxI4-VOkWYi7gD9iDq7gA4OolBpmDDnlqeIRP1ClKoNEIpEke_ZFLduB2S8SxxAUonHYv2WYnO9Lcs-7Ml-tT7PCsPtWkKq8sP9eguGZw2gHAo4SwlnrH56N2AgScQVprcOMckv9zHonSFoNAfSL-pzbrwBBpalwF86iOmH",
        description: "In ấn giá rẻ cho sinh viên, phục vụ 24/7.",
        phone: "090 123 4567"
    },
    {
        id: 5,
        name: "Quán Bún Chả Sinh Từ",
        type: "Quán ăn",
        categoryIcon: "restaurant",
        rating: 4.8,
        distance: "200m",
        location: "Gần cổng trường",
        price: "35.000đ - 55.000đ",
        priceValue: 55000,
        nearUniversities: ["ĐH Ngoại thương", "ĐH Kinh tế Quốc dân"],
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAosIxn72Ktbf2Ukxc32qu_vsJI2UQU2q2GfgSJg352Uf7pon_3zQNs6j4UYX96QO7QX7AFOUowTqaTlTFrxMfALZN80VKSJ1EODMTiVjKT3kcvg2miex0RdEwAsAgwe-8ihloxihvn3vXo8je43OtAbWikHMP2n7LQq53RdAV9sPfmF2DvN29Gu6vyP2CdzYCePVpLYAJx3JNJVZDu3yFhOIWjRpRBG4Bmt7YpJg4VwB3Z-o11kGWqIlciO2VBserqfzH7cv_BVee0",
        description: "Bún chả Hà Nội ngon chuẩn vị.",
        phone: "090 123 4567"
    },
    {
        id: 6,
        name: "Ký túc xá chất lượng cao",
        type: "Phòng trọ",
        categoryIcon: "bed",
        rating: 4.5,
        distance: "N/A",
        location: "An ninh 24/7",
        price: "Full nội thất",
        priceValue: 3000000,
        nearUniversities: ["ĐH Quốc gia TP.HCM", "ĐH Ngoại thương", "ĐH Kinh tế Quốc dân"],
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBGv268EcrTwfSzUUFIsQNBjcc4WrfyHpiVd1L7KVK0popPsuKHp-Qu4tK4O1o0DxtkN5an7BPWhqHSZpv3meXoD7Y7w7ZjicNN6AGPE12IxRjibcHqmtC3Y25JvOMTHCRWjBt6VAD8218hhmdb3Ltv2RW9ZJEDW7dSDeWKH-JPu7cF6yULOOAHNisQlfPhThKHvqYygzY86qpWDhHY0kJtcO3OrSD8cAgk1lLL72JtZkirNLOmMLN2DSM03m1JpH_1WqCD07umfJHx",
        description: "Phòng ở khép kín, tiện nghi đạt chuẩn.",
        phone: "090 123 4567"
    },
    {
        id: 7,
        name: "Tiệm Giặt Là Tự Động",
        type: "Dịch vụ",
        categoryIcon: "home_repair_service",
        rating: 4.9,
        distance: "50m",
        location: "Sấy khô lấy ngay",
        price: "Giá sinh viên",
        priceValue: 20000,
        nearUniversities: ["ĐH Bách Khoa", "ĐH Kinh tế Quốc dân", "ĐH Quốc gia TP.HCM"],
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBaDmPP_ceYJjkvBOWfuPPa1NDSc5TUAE3U470P7fPO-CJxkDtWqQ_35f9Tb4eUoF6rr-vV97Y7Qs64DgEds9YGPmB8W5VnLMSaKf8h6XW7LQClmwlu9xcOW5ywh5kdc35BJEU3R_9MoV0O9YyIkVyVtd4zT4n5ff4mlUjcRjcylODUmaUoZxOryyXQx6kN3kxKaTWYS8zr_ATRyIUV9sP-as8JG3m0L7cSmQp53K-a_6HhAqOd2bvz0EnEvmc09Yoj6OWW5HorIHuj",
        description: "Hệ thống máy giặt sấy hiện đại.",
        phone: "090 123 4567"
    },
    {
        id: 8,
        name: "Quiet Corner Cafe",
        type: "Quán ăn",
        categoryIcon: "restaurant",
        rating: 4.7,
        distance: "300m",
        location: "Mở 24/7",
        price: "Có ổ cắm",
        priceValue: 40000,
        nearUniversities: ["ĐH Ngoại thương", "ĐH Bách Khoa", "ĐH Quốc gia TP.HCM"],
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDz1OT11JwHNZZceTv9UqKXvwCrKVlRT9vhqhv9aiAYk1Eg7eSMlndrERdrntYcURd8JlMfC9zzcXT4--GJjEUNmZ3S_14ZazIl2FXLYv76e0V2qhyzUVCmEI5_k7S4i3nKbKXdcVKtgCxrooUjbOouV4_7hJIV4cXYz-1RTYSS8WKwtpo5PmMwpOFDQjPFDEizzBG0jfZ5qs1S_r83BylUD8198wdAwm5vRJ-u_QE_0jCKWvfd4RoguZb_N5shw_XWH_zaT0XeaiNd",
        description: "Nơi lý tưởng để học bài thâu đêm.",
        phone: "090 123 4567"
    },
    {
        id: 9,
        name: "Mì Ramen Oishii",
        type: "Quán ăn",
        categoryIcon: "restaurant",
        rating: 4.6,
        distance: "1km",
        location: "Khu BMT",
        price: "Ưu đãi 10% thẻ SV",
        priceValue: 60000,
        nearUniversities: ["ĐH Kinh tế Quốc dân", "ĐH Ngoại thương", "ĐH Bách Khoa", "ĐH Quốc gia TP.HCM"],
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB8LOHmAwxzUIeT8Q-TXHjLdFzzXWGciglS_XrdZqlnPShGUUFGddPMZA2nJwmDV_4PkUmpYPVRRn3tStDdxVgTUAYbg3Utec3WpU2ifOHJqZhpF3Jhq5nQhAfCXB8Vr4CMJhMYghjWVY9BTPEPespnZC_7y6P4RfprWHFcnwvgvhNsO-fasR54VqsYRRKfs_mihQENi9bAU4uPX0CP9byImsVn_RnQXzGLuHbNH3bvUzUSW-elrim1q6YKNkJ-wL8K_h6p4caw3mrg",
        description: "Mì ramen đậm chất Nhật.",
        phone: "090 123 4567"
    }
];
